### PR TITLE
Add support for Python 3.12

### PR DESCRIPTION
**Pull request by pauloxnet**
Ref #372

### CODE REVIEW

**Comment by pauloxnet** [comment]
Can you help us finalize this PR?

Tests with Python 3.12 and Django 5.0 are failing with this traceback:

```pycon
  Traceback (most recent call last):
    File "/home/runner/work/django-configurations/django-configurations/.tox/py312-djmain/bin/django-cadmin", line 8, in <module>
      sys.exit(execute_from_command_line())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/django-configurations/django-configurations/.tox/py312-djmain/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
      utility.execute()
    File "/home/runner/work/django-configurations/django-configurations/.tox/py312-djmain/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
      self.fetch_command(subcommand).run_from_argv(self.argv)
    File "/home/runner/work/django-configurations/django-configurations/.tox/py312-djmain/lib/python3.12/site-packages/django/core/management/commands/test.py", line 24, in run_from_argv
      super().run_from_argv(argv)
    File "/home/runner/work/django-configurations/django-configurations/.tox/py312-djmain/lib/python3.12/site-packages/django/core/management/base.py", line 404, in run_from_argv
      parser = self.create_parser(argv[0], argv[1])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/django-configurations/django-configurations/configurations/importer.py", line 35, in create_parser
      parser = orig_create_parser(self, prog_name, subcommand)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/django-configurations/django-configurations/.tox/py312-djmain/lib/python3.12/site-packages/django/core/management/base.py", line 367, in create_parser
      self.add_arguments(parser)
    File "/home/runner/work/django-configurations/django-configurations/.tox/py312-djmain/lib/python3.12/site-packages/django/core/management/commands/test.py", line 54, in add_arguments
      test_runner_class = get_runner(settings, self.test_runner)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/django-configurations/django-configurations/.tox/py312-djmain/lib/python3.12/site-packages/django/test/utils.py", line 370, in get_runner
      test_runner_class = test_runner_class or settings.TEST_RUNNER
                                               ^^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/django-configurations/django-configurations/.tox/py312-djmain/lib/python3.12/site-packages/django/conf/__init__.py", line 75, in __getattr__
      self._setup(name)
    File "/home/runner/work/django-configurations/django-configurations/.tox/py312-djmain/lib/python3.12/site-packages/django/conf/__init__.py", line 62, in _setup
      self._wrapped = Settings(settings_module)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/runner/work/django-configurations/django-configurations/.tox/py312-djmain/lib/python3.12/site-packages/django/conf/__init__.py", line 160, in __init__
      mod = importlib.import_module(self.SETTINGS_MODULE)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/hostedtoolcache/Python/3.12.0/x64/lib/python3.12/importlib/__init__.py", line 90, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1318, in _find_and_load_unlocked
  ModuleNotFoundError: No module named 'tests'
```

**Comment by tonybaloney** [comment]
I would check (in this order)

- Have the dependencies been tested with Python 3.12
- Check that you're testing the installed version
- look at setup.py. You might need to use one of the functions that does package discovery. Lots of things changed around setuptools in the last version (which comes bundled with Python 3.12) https://setuptools.pypa.io/en/latest/deprecated/changed_keywords.html

**Comment by felixxm** [comment]
> Tests with Python 3.12 and Django 5.0 are failing with this traceback:

Test settings cannot be imported. My gut feeling is that tricky things that `Configuration` and `ConfigurationBase` do in `__new__` are not compatible with Python 3.12.

**Comment by pauloxnet** [comment]
> > Tests with Python 3.12 and Django 5.0 are failing with this traceback:
> 
> Test settings cannot be imported. My gut feeling is that tricky things that `Configuration` and `ConfigurationBase` do in `__new__` are not compatible with Python 3.12.

@felixxm thanks for your comment. I'll try to dig it a bit, but it 
I'll try to delve a little deeper into your hypotheses, if correct it would mean that this package could not be updated to Python 3.12 :-(

**Comment by miketheman** [comment]
@pauloxnet I was tinkering with this, and found that if we explicitly add `setuptools` and `wheel` deps to tox, we can get a running test suite.

I don't know the correct way to express multiple deps for a given tox env, but this patch ought to complete a full test suite.

```diff
diff --git a/tox.ini b/tox.ini
index 894b461..6e1692a 100644
--- a/tox.ini
+++ b/tox.ini
@@ -31,6 +31,8 @@ deps =
     dj42: django~=4.2.0
     dj50: django~=5.0.0a1
     djmain: https://github.com/django/django/archive/main.tar.gz
+    py312: setuptools
+    py312: wheel
     coverage
     coverage_enable_subprocess
 extras = testing
```

**Comment by pauloxnet** [comment]
> @pauloxnet I was tinkering with this, and found that if we explicitly add `setuptools` and `wheel` deps to tox, we can get a running test suite.

Thanks for finding the fix. I applied your suggested additional dependencies and the pipeline with Python 3.12 now no longer fails.

**Review by niccolomineo — APPROVED** [review]

**Pull request merged**
