### PR TITLE
Update release.yml

### PR DESCRIPTION
**Pull request by jannisleidel**

### CODE REVIEW

**Comment by jannisleidel** [comment]
@aleksihakli Hey, can you review this PR just to check if the CODEOWNERS file I just added worked?

**Comment by jezdez** [comment]
@aleksihakli Obviously the previous commit was me ;)

**Comment by jannisleidel** [comment]
Oh, and can you check if you would be able to actually merge the PR as well?

**Comment by aleksihakli** [comment]
Sure thing, I'll check this today.

**Review by aleksihakli — APPROVED** [review]
Looks silly good to me!

**Comment by aleksihakli** [comment]
After approval merging seems to be available @jannisleidel @jezdez 

Screenshot_20210119-164738

**Pull request merged**
