### PR TITLE
0.9 Release

### PR DESCRIPTION
**Pull request by skolsuper**
This incorporates both @jrdietrick and @blueyed open PRs, bumps version to 0.9 and updates the changelog.  I think give it a week for review and comment and then release a new version for christmas :)

### CODE REVIEW

**Comment by skolsuper** [comment]
Going forward,  I think we need to update the contribution guidelines and set up a process for merging PRs for a project with no hierarchy.  Is there another OSS project that has managed this already that we could use as an example?  bitcoin/bitcoin maybe?: 

https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md#decision-making-process

**Comment by ticosax** [comment]
@skolsuper since you raise the topic, there is an interesting reading here:
http://hintjens.com/blog:106

We have the opportunity to try something new, thanks to jazzband. We could try to keep it as open as possible and see what is happening.
I'd make only one rule to start:
 - We accept merges only from another contributor, not from the submitter (unless trivial changes like typos or documentation.)

Regarding testing, we can rely on codecov or similar service. Then we know when tests are lacking, we don't need to patronize each other.

When a merged contribution is challenged, then we discuss with another pull request. In fact everything is explained by Pieter Hintjens in its blog post how it would work.

**Comment by skolsuper** [comment]
@ticosax super interesting blog post, and I'd love to give that a try!

BUT

*For this repo specifically*, because of the situation for the last 9 months or so since Django 1.8 came out, there are going to be an abnormally high number of people pulling from the master branch.  Therefore I think we have to be very careful with this branch for a while.

With that said, I'm not going to veto the idea.  Maybe we could do something like cut releases from a 0.9x branch and use OM on that only.

**Comment by ticosax** [comment]
Developers are not forced to pin their dependencies with master branch, they can target a specific commit instead, even if it points also to master@HEAD. If they do, this is their responsibility, I wouldn't be to worry about people shooting themselves in the foot. We have enough on our plate.

Shall we move this conversation to `jazzband/roadies` ?

**Comment by jezdez** [comment]
Having my django-configurations developer hat on I'd like to urge you to move on and get an official release out. Depending on git repos as a dependency is a bug and should not be catered to.

I know this isn't nice for some and definitely a side effect of not having done a release for a long time, so it's me to blame for this. But we now have the ability to break free of this situation and shouldn't fall into the trap of accepting a work around as the new normal. PyPI is the canonical source of Python package releases, we must work toward using that and cover the short period of time of fixing the work around by helping with documentation and public announcements. In that sense I also think we should call the release 1.0 to give it enough attention for the users.

**Comment by ticosax** [comment]
Is it possible to rebase it against master ? assuming the PR you depend on, are merged ?

**Comment by blueyed** [comment]
#131 is not yet merged, but I agree that it should get merged independently / before already, so that all PRs can be rebased and tests would be fixed.

**Comment by skolsuper** [comment]
@ticosax this PR can be fast-forwarded onto master.

I have bumped and tagged release number to 1.0.0 (added 3rd number for bugfixes in line with jazzband guidelines).

**Comment by skolsuper** [comment]
@blueyed #131 is merged into this branch already, I don't know if github will detect that and close it as merged, I should hope it does though.

**Comment by blueyed** [comment]
@skolsuper 
I know, but given that this might be open / discussed a bit longer, it would be good to get it merged already / first.  However, I'd be also fine with merging this from this PR soon / today, but then maybe as `rc1` first?

**Comment by blueyed** [comment]
..in the end however, it (this PR) should be (interactively) rebased / cleaned up probably.

**Comment by skolsuper** [comment]
Okay it seems to me like the consensus is to get things moving and not let the perfect be the enemy of the good here.  It seems likely there are no breaking changes in this from current master anyway, so if someone wants to go ahead and merge this they have a :+1: from me.

**Comment by blueyed** [comment]
I've merged #131 now, please re-base.

**Comment by skolsuper** [comment]
...

**Comment by blueyed** [comment]
@skolsuper ?
There were 3 thumbs up on #131, and the rebase should be trivial (and should have been done anyway).

There's also the fact that this PR needs some more discussion (rc?).

The most pressing point for contributions is now fixed, so let's go from there.

**Comment by skolsuper** [comment]
This PR contained #131, it doesn't require a rebase.

**Comment by blueyed** [comment]
It required a rebase (IMHO) before already (I've mentioned it): the changelog/version should be in a single commit and there should be no merge commits.

Having a PR with merges is good for having Travis verifies that it works, but it should not be in the repo.

Apart from that I've stated in https://github.com/jazzband/django-configurations/pull/124 that https://github.com/jazzband/django-configurations/pull/128 seems to be better in terms of test coverage.  #128 is in master by now, through #131.

Since you have resolved the conflicts already when creating this PR, and you're hopefully using rerere (https://git-scm.com/blog/2010/03/08/rerere.html), it will be trivial (hopefully) to rebase it.

This is what I expect it to be: https://github.com/jazzband/django-configurations/compare/master...blueyed:rebased-pr132

**Comment by blueyed** [comment]
Apart from that: should we go with 1.0.0 directly, or have a rc before, which would also allow us to test the whole release procedure?

**Comment by skolsuper** [comment]
This branch was supposed to represent the state of master after merging #124 and #131, it's unnecessary if we're gonna merge those independently.  Feel free to cherry pick + squash the changelog commits.

**Comment by jezdez** [comment]
@blueyed Yes

**Comment by jezdez** [comment]
Oh, and another thing, there is no need to require "clean" commits here, in my experience many contributors don't know enough about git to do complex rebases and making it a requirement for "good" PRs counteracts the notion of being welcoming to everyone no matter the skill level. Don't hesitate to use it for your own PRs of course, but don't enforce it on others for now. </configurations dev>

**Comment by jrdietrick** [comment]
#124 is cleaned up anyway :)

**Comment by skolsuper** [comment]
I think @blueyed and I have been talking past each other itt, this PR was intended to be like a "release branch" from gitflow, not really a traditional github PR with features or fixes.

**Comment by skolsuper** [comment]
I do know enough git to squash the redundant commits (enough to be dangerous :D) but I figured I would just do that when merging.

**Comment by blueyed** [comment]
@jezdez 
> @blueyed Yes

I don't understand it: would you prefer a 1.0.0 release right away, or a rc before?

**Comment by jezdez** [comment]
I don't think a rc is needed. Coverage is good, lots of people here have run the current master code and frankly I'd rather roll forward in case something is wrong. I also haven't seen much buy-in from others here to have a rc.

**Pull request closed without merging**
