### PR TITLE
Add stub release note for v1.1

### PR DESCRIPTION
**Pull request by ticosax**
Encourage developers to contribute to the changelog as they go.

### CODE REVIEW

**Comment by blueyed** [comment]
:+1:

**Comment by slafs** [comment]
Just in case, I'd like to point out how jazzband documents [releases](https://jazzband.co/docs/releases) in "How to decide for the version number?" (with BREAKING.FEATURE.FIX numbering). I made a similar comment in https://github.com/jazzband/django-pipeline/issues/515.

It would be great if we could stick to that.

**Comment by ticosax** [comment]
@slafs you are right it could be `1.0.1` instead. I'll change it. Anyway we will decide the version number when doing the release.

**Comment by slafs** [comment]
Thanks. 
> Anyway we will decide the version number when doing the release.

Yes, of course.

**Comment by blueyed** [comment]
Maybe we should also bump the version in `configurations/__init__.py` already - to `1.X-dev`?

**Comment by mauricioabreu** [comment]
@blueyed Agreed! After every release the version should be changed. This way dev releases will be installed.

**Comment by ticosax** [comment]
@blueyed good point, thanks. #139

**Pull request merged**
