### PR TITLE
Fix tests and travis

### PR DESCRIPTION
**Pull request by blueyed**
This includes #126 and #128.

 - [x] needs cleanup/amend/rebase

### CODE REVIEW

**Comment by blueyed** [comment]
Amended/cleaned up.
Has been tested in https://travis-ci.org/jazzband/django-configurations/builds/97554768.

**Comment by blueyed** [comment]
This is ready.
Please review.

**Comment by ticosax** [comment]
:+1: on my side.

**Comment by jpadilla** [comment]
Looks good to me too

**Comment by mauricioabreu** [comment]
Looks good to me.
Good job on handling Travis configuration. :+1:

**Comment by blueyed** [comment]
Merged, thanks for your feedback!

**Pull request merged**
