### PR TITLE
Changelog for release 1.0

### PR DESCRIPTION
**Pull request by ticosax**
Based on #132 
Ideally, can be merged after:

- [x] #135 
- [x] #124

### CODE REVIEW

**Comment by jezdez** [comment]
:boom: :cake: :balloon: :fireworks:

**Comment by blueyed** [comment]
:+1:

**Comment by ticosax** [comment]
We tested against our project. Current master d827664e92a2561b9c55722985861694b2861611  seems good to go for `v1.0`.

**Comment by blueyed** [comment]
It's also green in pytest-django's test suite: https://github.com/pytest-dev/pytest-django/pull/304

**Comment by ticosax** [comment]
whoua ! never a release has been so easy to publish.

https://pypi.python.org/pypi/django-configurations/1.0

@jezdez You did something really awesome with jazzband. Thank you ! :sunny:

**Comment by jezdez** [comment]
@ticosax \o/ YAY!!

**Pull request merged**
