### PR TITLE
tests: use coverage_enable_subprocess instead of sitecustomize.py

### PR DESCRIPTION
**Pull request by blueyed**
Thanks @asottile.

### CODE REVIEW

**Comment by blueyed** [comment]
Thanks to both of you! :)

**Comment by jezdez** [comment]
@blueyed This broke the deployment since the deploy step depends on the existence of the `TOXENV` env variable.

**Comment by blueyed** [comment]
@jezdez logs?
Are you confusing this with another change?  (TOXENV should not be "lost" due to this, is it?)

**Comment by blueyed** [comment]
I see: `condition: "$TOXENV = py36-dj111"`, sorry.

**Comment by jezdez** [comment]
Yeah, no worries, I'll fix this in #248. Sorry for the noise! 😬

**Pull request merged**
