### PR TITLE
Drop support of python 2.6, 3.2 and Django < 1.8

### PR DESCRIPTION
**Pull request by ticosax**

### CODE REVIEW

**Comment by blueyed** [comment]
:+1: 

That should become `1.1.x` then probably.

**Comment by jezdez** [comment]
This should become `2.x` as it's a breaking change

**Comment by jezdez** [comment]
Hm, at least I think it should, I've raised the question to the lazy web: https://twitter.com/jezdez/status/690143400444698624

**Comment by ticosax** [comment]
I think `2.x` suits better.

**Comment by jezdez** [comment]
@ticosax Yeah, that seemed to be the majority answer on Twitter, too.

**Comment by mauricioabreu** [comment]
LGTM :+1:

**Comment by jezdez** [comment]
As this removes the documentation for the pre-made Django project templates, should we add new ones for 1.7 and above?

**Comment by ticosax** [comment]
@jezdez How did you created those templates ?
I never used those in the past. Please, pardon my ignorance :smile:

**Comment by jezdez** [comment]
@ticosax Manually :) I used the Django project templates and then modified them until they used some sensible defaults using django-configurations. At the time the project templates were still vastly changing, but there are still some things new in 1.8 and 1.9. Maybe at least create 1.8?

**Comment by blueyed** [comment]
FWIW, I'm with https://twitter.com/mgedmin/status/690147336740311041 and would not consider this a MAJOR change - otherwise every dropping of support for a Django version would mean to have a MAJOR bump.

But I'm -0 on this - it's fine (and why not have 2.0 after 1.0?! ;))
What I wanted to express from the beginning only is that this shouldn't be a PATCH release.. :)

**Comment by blueyed** [comment]
Given the number of Django versions being dropped, I'm also more +0 on using 2.x.. :)

**Comment by ticosax** [comment]
I pushed the branch https://github.com/jazzband/django-configurations/tree/templates/1.8.x
based on `templates/1.6.x`
You can see the [diff](https://github.com/jazzband/django-configurations/compare/templates/1.6.x...templates/1.8.x?expand=1) to compare.

**Comment by ticosax** [comment]
Templates and documentation are back ! just for 1.8

**Comment by blueyed** [comment]
:+1

**Comment by jezdez** [comment]
@ticosax Woohoo!

**Comment by mauricioabreu** [comment]
Good job :+1:

**Pull request merged**
