### PR TITLE
GitHub Actions: Upgrade the release workflow to Python 3.13

### PR DESCRIPTION
**Pull request by cclauss**
https://github.com/actions/setup-python/releases

### CODE REVIEW

**Review by pauloxnet — APPROVED** [review]
Sorry for the delay.

Welcome aboard ⛵️!

**Comment by uhurusurfa** [comment]
@pauloxnet - do you have permissions to trigger a rerun of the tests for this PR now that the codecov issue has been resolved?

**Comment by cclauss** [comment]
Perhaps drop Py38 and add Py313

**Comment by uhurusurfa** [comment]
> Perhaps drop Py38 and add Py313

Sure - go ahead and make the change

**Comment by pauloxnet** [comment]
> @pauloxnet - do you have permissions to trigger a rerun of the tests for this PR now that the codecov issue has been resolved?

I just did it, but Python 3.13 tests are failing.

**Comment by pauloxnet** [comment]
> Perhaps drop Py38 and add Py313

Yes, drop Python 3.8 which is EOL and update the PR title accordingly.

**Pull request merged**
