### PR TITLE
specify we are developing a new version.

### PR DESCRIPTION
**Pull request by ticosax**
Version pattern follows the recommendation described by pep440.
https://www.python.org/dev/peps/pep-0440/#development-release-separators

### CODE REVIEW

**Comment by mauricioabreu** [comment]
:+1: 
+1 for linking PEP.

**Comment by mauricioabreu** [comment]
I know it is not probably documented as a rule and I am being a boring person here. But it is a good thing to write commit messages with the first word capitalized.

"Specify we are developing a new version"

**Comment by atugushev** [comment]
I like [this concept](http://chris.beams.io/posts/git-commit/) for commit messages. It  would be nice to write a rules for that.

**Comment by ticosax** [comment]
@mauricioabreu Thanks for the suggestion. While I'll try to keep this advice in mind. I'm not convinced we should be so picky about such rules. Sometimes, some cosmetic rules, like [pep8](https://www.youtube.com/watch?v=wf-BqAjZb8M), distract us from the real problems and might create barrier for newcomers.

**Comment by mauricioabreu** [comment]
@ticosax agreed. Your PR looks good to me.

**Comment by blueyed** [comment]
Cherry-picked it with an amended commit message (ACKed).

Regarding best practises https://github.com/codingjoe/django-cc is interesting!

**Pull request closed without merging**
